name: Deploy to GitHub Pages

on:
  # Wird bei jedem Push auf main ausgeführt
  push:
    branches:
      - master

  # Ermöglicht manuelles Triggern aus dem Actions-Tab
  workflow_dispatch:

# Setzt Berechtigungen für GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Erlaubt nur ein gleichzeitiges Deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4